# -*- coding: utf-8 -*-
"""CGPA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G14EGVXXgiybWUG91dgp1VfB_RAmjXQB
"""

def grade_points():
    return {
        'A+': 4.00, 'A': 3.75, 'A-': 3.50, 'B+': 3.25, 'B': 3.00,
        'B-': 2.75, 'C+': 2.50, 'C': 2.25, 'D': 2.00, 'F': 0.00
    }

def credit_options():
    return [0, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 2.25, 2.5, 2.75, 3, 3.25, 3.5, 3.75, 4]

def show_menu(items, message):
    print(f"\n{message}")
    for i in range(len(items)):
        print(f"{i+1}. {items[i]}")
    while True:
        try:
            choice = int(input("Enter your choice number: "))
            if 1 <= choice <= len(items):
                return items[choice - 1]
            print(f"Please choose a number between 1 and {len(items)}")
        except ValueError:
            print("Invalid input. Please enter a number.")

def compute_cgpa(data):
    total_gp = 0
    total_ch = 0
    last_gp = 0
    last_ch = 0

    for sem, subjects in data.items():
        for gp, ch in subjects:
            total_gp += gp * ch
            total_ch += ch
            if sem >= 5:
                last_gp += gp * ch
                last_ch += ch

    overall = total_gp / total_ch if total_ch > 0 else None
    last_2_years = last_gp / last_ch if last_ch > 0 else None
    return overall, last_2_years

def main():
    print("\n=== CGPA Calculator ===\n")
    print("Enter your grades and credits for each semester.\n")

    grades = list(grade_points().keys())
    credits = credit_options()
    grade_map = grade_points()
    all_data = {}

    try:
        for sem in range(1, 9):
            print(f"\nSemester {sem}")
            course_count = show_menu([str(i) for i in range(11)], "How many courses? (0 to skip):")
            course_count = int(course_count)
            subjects = []

            for c in range(1, course_count + 1):
                print(f"\nCourse {c}")
                g = show_menu(grades, "Select grade:")
                ch = float(show_menu([str(c) for c in credits], "Select credit:"))
                subjects.append((grade_map[g], ch))

            all_data[sem] = subjects

        overall, last_2 = compute_cgpa(all_data)

        print("\n=== Results ===")
        if overall is not None:
            print(f"Overall CGPA: {overall:.2f}")
        else:
            print("Overall CGPA: Not available")

        if last_2 is not None:
            print(f"Last 2 Years CGPA (Sem 5–8): {last_2:.2f}")
        else:
            print("Last 2 Years CGPA: Not available")

        with open("cgpa_results.txt", "w") as file:
            file.write("=== CGPA Results ===\n")
            file.write(f"Overall CGPA: {overall:.2f}\n" if overall else "Overall CGPA: Not available\n")
            file.write(f"Last 2 Years CGPA: {last_2:.2f}\n" if last_2 else "Last 2 Years CGPA: Not available\n")
            file.write("=" * 30)
        print("Saved to cgpa_results.txt")

    except KeyboardInterrupt:
        print("\nStopped by user.")
    except Exception as err:
        print(f"\nSomething went wrong: {err}")

if __name__ == "__main__":
    main()